### ISSUE TITLE
Theme and Plugin in one Project

### ISSUE THREAD

**Issue by Vanillabacke** [swashata/wp-webpack-script#1085]
Hi, at first thanks for that awesome work!

Is it possible to have the theme and the plugin combined in a single project?
In my case, the plugin and theme are strongly connected with some blocks, so they are sharing some stuff in the source files and it would be nice to run just only one task.

For example:
```
src folder
  - plugin
      -  entry.js -> export to plugin
  - theme
      -  entry.js -> export to templates
  - sharedStuff
```

**Comment by ajgagnon** [comment]
I'm not the author if this repo, but perhaps you could use something like lerna to accomplish this:

https://github.com/lerna/lerna

You can see how WordPress set it up on their gutenberg example blocks project - each block has it's own package.json and you can run one command to rule them all 👹

https://github.com/WordPress/gutenberg-examples

**Comment by Vanillabacke** [comment]
> I'm not the author if this repo, but perhaps you could use something like lerna to accomplish this:
> 
> https://github.com/lerna/lerna
> 
> You can see how WordPress set it up on their gutenberg example blocks project - each block has it's own package.json and you can run one command to rule them all 👹
> 
> https://github.com/WordPress/gutenberg-examples

@ajgagnon thank you for sharing lerna, never heard of it yet. but it looks like an workaround, guess this will be the wrong solution. Currently I'm digging into an self written config for now.

The examples of gutenberg itself are just for some basic block development. I'm writing an template which has its own optimized blocks without having some heavy load stuff going on. the plugin and the theme are sharing a lot of stuff and if one of the common files were changed, it should update automatically both of them.

but thanks a lot!

**Comment by swashata** [comment]
Hi,

You can use separate project config. Like

```bash
yarn start -p ./plugin.wpackio.project.js -s ./plugin.wpackio.server.js
yarn start -p ./theme.wpackio.project.js -s ./theme.wpackio.server.js
```

We have documentation here https://wpack.io/commands/wpackio-scripts/#cli-parameters
