### ISSUE TITLE
Passing a Custom NODE_ENV

### ISSUE THREAD

**Issue by ajgagnon** [swashata/wp-webpack-script#1092]
Absolutely love this project!

Had a question about passing a custom NODE_ENV or a custom environmental variable to the script. 

It seems this kind of stuff doesn't work:

```
cross-env NODE_ENV=staging wpackio-scripts start
```

Or

```
cross-env MY_ENV=staging wpackio-scripts start
```

Is there an easy way to do this that I'm missing?

Thanks so much.

**Comment by ajgagnon** [comment]
Sounds good! I'd be happy to. Wondering if there needs to be a prefix? This was my current thinking - something like this:

https://github.com/ajgagnon/wp-webpack-script/pull/1/commits/f525276833a272706fc2ed4e8ac9ae717360cd47

Or is there a really strong reason do to a prefix? It would be great to have more control over webpack this way.

**Comment by swashata** [comment]
The approach is great. But having a clear prefix means users would know which env values are exposed to the front-end script. We wouldn't want any private key to leak in there. For example, one may have some sensitive information stored in env to be used during tests. We wouldn't want that to be copied and exposed to client side script. With a prefix like, WPACKIO_APP we are essentially taking consent from the user.

**Comment by ajgagnon** [comment]
Added a PR here, so I'm closing this out!

https://github.com/swashata/wp-webpack-script/pull/1134
