### ISSUE TITLE
Doesn't compile when run yarn start

### ISSUE THREAD

**Issue by izundo-viennv** [swashata/wp-webpack-script#1114]
When I run `yarn start`, then the dist folder just only have manifest.json file, but If I run `yarn build`, then the dist folder will have js, css files.

This is for` yarn start`
![image](https://user-images.githubusercontent.com/29116432/96360899-62a2fc00-114b-11eb-85d2-4d6422e850a2.png)

This is for `yarn build`
![image](https://user-images.githubusercontent.com/29116432/96360927-91b96d80-114b-11eb-9f67-6a86bba1138e.png)

**Comment by swashata** [comment]
This is expected. During development files are served from the memory by the proxy server.

**Comment by swashata** [comment]
Closing since no reply
