### ISSUE TITLE
EntryPoint handle for wp_localize_script()

### ISSUE THREAD

**Issue by Mallinanga** [swashata/wp-webpack-script#116]
How does wpack.io handle localisation of strings within the scripts?

Using a vanilla WordPress install, one can do wp_localize_script('scriptHandle', 'globalVariable', $array);

But now that wpack.io takes over the registration and enqueueing of the assets, how can we know the handle of a specific script so we can call wp_localize_script() on it?

**Comment by swashata** [comment]
This has been published https://wpack.io/tutorials/localize-script/
