### ISSUE TITLE
Path of assets is not correct when called from .scss files

### ISSUE THREAD

**Issue by Mallinanga** [swashata/wp-webpack-script#117]
Hello,

For some weird reason, if I import let's say an image from within a .js file and console.log it, the url is correct.
But if I reference the same image from within an .scss file then I get a 404 because the url has the entrypoint name twice in the url
eg:

`import image from '../img/about-bckr.jpg';`

Correct url when imported from a .js file:
`http://somehost/wp-content/themes/vg-twig/build/app/assets/asset-601792add27d5248500ec253301b723d.jpg`

`
body {
    background: #f1f1f1 url(../img/about-bckr.jpg);
}
`

Wrong url when imported/called from an .scss file:
`http://somehost/wp-content/themes/vg-twig/build/app/app/assets/asset-601792add27d5248500ec253301b723d.jpg`

Notice the double `/app/app/` there.

**Comment by swashata** [comment]
Thanks, I can confirm this bug and will fix it in the next release.
