### ISSUE TITLE
JavaScript code is not working, but importing SASS file from JavaScript itself works?

### ISSUE THREAD

**Issue by KoichaDev** [swashata/wp-webpack-script#1176]
Right, this might sound weird. I have an `index.js` file that works if I do  `import './sass/main.scss';` 

If I try to do `console.log('test') `or `alert('test')` on the `index.js`, then it's not working at all. 

What is the cause of this issue here?

**Comment by swashata** [comment]
Maybe the file needs to be a module. Try this

```
export default undefined;

console.log('test');
```
