### ISSUE TITLE
Feature Request: wpackio-scripts watch

### ISSUE THREAD

**Issue by Mallinanga** [swashata/wp-webpack-script#118]
Would it be possible to have an extra command like

`wpackio-scripts watch`

that does pretty much what build does but keep watching for file changes and recompile?

The fact that `wpackio-scripts start` does not output any files on the filesystem while it runs gives me a bit the chills, when I imagine a possible power outage after hours of developing.
And yes I know UPS exist :)
But since `watch` mode is already included in webpack, why not have a command that does that?

Please consider it. :)
Thank you

**Comment by Mallinanga** [comment]
I was thinking again about this, and maybe this feature request might mean a whole lot code re-writing on your part.

So, might I suggest something else?

How about having a function somewhere that we can use in a new webpack.config.js that "gets" the generated webpack config from .wpackio.project.js?

That way we can simply call `webpack -w --config ./webpack.config.js` without interfering with wpackio's internals.

Just a thought. :)

**Comment by swashata** [comment]
<blockquote>The fact that wpackio-scripts start does not output any files on the filesystem while it runs gives me a bit the chills, when I imagine a possible power outage after hours of developing.</blockquote>

That's the thing now! You don't need to track your output bundle. You just need to save the source file, and no matter how many times you run `wpackio-scripts start` or `wpackio-scripts build`, it will always create the right file.

So be assured that you don't need to make sure the `dist` exists. I personally do not recommend tracking it on your VCS too. As long as your source files are there you are just safe.
