### ISSUE TITLE
Dumb but needed question: Can i still develop my theme with normal wordpress php or i have to use react?

### ISSUE THREAD

**Issue by Lolosan** [swashata/wp-webpack-script#1182]
I've come across to wpack.io while dealing with a new woocommerce theme with bootstrap sass + all that i can find to automate (minify, stripping unused components, etc)

But i've read this: "All the stuff you need to start developing using react. Hello Gutenberg!" in the homepage

So my question is: I have to create a react theme o i can still use wpack and normal oldschool wordpress/woocommerce php?

**Comment by swashata** [comment]
Hello,

No worries at all. To answer your question, yes you can use normal oldschool WordPress/WooCommerce PHP with the tooling. While the primary focus of the tooling is to enable using modern libraries like React within WordPress plugins/themes, it is totally possible to not use it. Infact, during bootstrap, the question is asked and using react is always opt-in.

In any case, the tooling will always build assets (JS/SASS/LESS etc), minify and optimize for production and will give you a nice hot-reloadable server for development.

**Comment by Lolosan** [comment]
Thank you very much for your answer!
