### ISSUE TITLE
wpackio.project.js Not Found by wpackio-scripts start

### ISSUE THREAD

**Issue by chet-tbf** [swashata/wp-webpack-script#1186]
I just discovered wpack.io tonight and was hoping to quickly get my project spun up. However after going through all of the set-up, and attempting to run `yarn start` I get the following issues:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/67376875/112251275-f1e79a80-8c28-11eb-8201-d967b0a32d43.png">

As you can see the file is present in the directory, but for some reason the script isn't seeing it.

My first thought was perhaps its a permissions issue, but I changed the permissions to be very open on both `wpackio.project.js` and `wpackio.server.js` to no avail.

Any advice here is greatly appreciated.

**Comment by swashata** [comment]
Hi,

This could also happen if `require` gives something invalid. Do make sure the content inside `wpackio.project.js` is valid JavaScript.

**Comment by chet-tbf** [comment]
Thank you for the heads up there! I had a problem with the way I had originally formed something in the `alias` object.
