### ISSUE TITLE
npm run bootstrap throws error: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by janelmer** [swashata/wp-webpack-script#1220]
**After installing the v6.0.1 Version and running "npm run bootstrap" it produces this error:**
__      __
\ \ /\ / / PACK.IO
 \ V  V /  JavaScript tooling for WordPress
  \_/\_/   v6.0.1

📦 bootstraping wpack.io into your project
✖ something went wrong trying to bootstrap.
  TypeError: Cannot read property 'indexOf' of undefined
  
  - Bootstrap.js:213 
    [wpackio6]/[@wpackio]/scripts/lib/scripts/Bootstrap.js:213:36
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  
  - Bootstrap.js:112 async Bootstrap.bootstrap
    [wpackio6]/[@wpackio]/scripts/lib/scripts/Bootstrap.js:112:28
  
  - bootstrap.js:34 async bootstrap
    [wpackio6]/[@wpackio]/scripts/lib/bin/bootstrap.js:34:20

**Logfile**
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'bootstrap' ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prebootstrap', 'bootstrap', 'postbootstrap' ]
5 info lifecycle wpackio6@0.1.0~prebootstrap: wpackio6@0.1.0
6 info lifecycle wpackio6@0.1.0~bootstrap: wpackio6@0.1.0
7 verbose lifecycle wpackio6@0.1.0~bootstrap: unsafe-perm in lifecycle true
8 verbose lifecycle wpackio6@0.1.0~bootstrap: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/janelmer/coding/wpackio6/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle wpackio6@0.1.0~bootstrap: CWD: /Users/janelmer/coding/wpackio6
10 silly lifecycle wpackio6@0.1.0~bootstrap: Args: [ '-c', 'wpackio-scripts bootstrap' ]
11 silly lifecycle wpackio6@0.1.0~bootstrap: Returned: code: 1  signal: null
12 info lifecycle wpackio6@0.1.0~bootstrap: Failed to exec bootstrap script
13 verbose stack Error: wpackio6@0.1.0 bootstrap: `wpackio-scripts bootstrap`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid wpackio6@0.1.0
15 verbose cwd /Users/janelmer/coding/wpackio6
16 verbose Darwin 20.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "bootstrap"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error wpackio6@0.1.0 bootstrap: `wpackio-scripts bootstrap`
22 error Exit status 1
23 error Failed at the wpackio6@0.1.0 bootstrap script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by swashata** [comment]
Thank you for reporting. I am looking into it.
