### ISSUE TITLE
@wpackio/entrypoint 6 and wpackio/enqueue 3.1.0 are incompatible

### ISSUE THREAD

**Issue by robsonsobral** [swashata/wp-webpack-script#1222]
It took me some time, but I found the issue driving me crazy all day.

`wpackio/enqueue` looks for `assets` property within endpoint.

```php
$enqueue =
	isset( $manifest['wpackioEp'][ $entryPoint ]['assets'] )
		? $manifest['wpackioEp'][ $entryPoint ]['assets']
		: false;
```

But `@wpackio/entrypoint` creates a different structure:

```json
  "wpackioEp": {
    "main": {
      "js": [
        "app/runtime.js",
        "app/vendors~main.js",
        "app/main.js"
      ],
```

This is a total showstopper.

**Comment by robsonsobral** [comment]
I can fix it, @swashata . Just tell which path to take. To change the manifest structure? Or to make the PHP retrocompatible?

**Comment by swashata** [comment]
Hi @robsonsobral,

With the v6 update of `@wpackio/scripts`, I am using `webpack-assets-manifest` [4.0.6](https://github.com/webdeveric/webpack-assets-manifest/releases/tag/v4.0.0) which outputs the manifest like

```json
  "wpackioEp": {
    "main": {
      "assets": {
        "js": [
          "app/runtime.js",
          "app/vendors~main.js",
          "app/main.js"
        ],
      }
```

I think for some reason, `webpack-assets-manifest` is stuck at a previous version in your case. Do check your package.json or yarn resolution. Maybe remove the lock file and node_modules and reinstall?

**Comment by robsonsobral** [comment]
You're right, @swashata ! I'm so sorry for bothering you.

**Comment by swashata** [comment]
No problem at all. And thank you for the pr on docs 👍
