### ISSUE TITLE
Button Text size is too big. It can be reduced to look better.

### ISSUE THREAD

**Issue by Amitavo** [swashata/wp-webpack-script#17]
The text of the button is used 24Pt which is looking too big. 
If you reduce it to 20 pt I think it may look better.
Rest font weight may remain the same.
![wpack-io](https://user-images.githubusercontent.com/44457119/47476808-ca196000-d83f-11e8-99b7-d72c88ee5143.png)

**Comment by swashata** [comment]
Thanks. While you are at it, could you please also take a spin at the logo?

Here are the SVGs

**Symbol**
https://github.com/swashata/wp-webpack-script/blob/master/site/src/components/svgs/wpackio-symbol.svg

**Text**
https://github.com/swashata/wp-webpack-script/blob/master/site/src/components/svgs/wpackio-text.svg

**Comment by swashata** [comment]
It's been implemented. Do take a look at my other proposal. 👍

**Comment by Amitavo** [comment]
Have tried some logo design .. (rough sketch only) if you like the concept then I will proceed .
![whatsapp image 2018-10-27 at 11 22 09 am](https://user-images.githubusercontent.com/44457119/47600193-d71e8680-d9da-11e8-9a09-dd1d29d5fb0e.jpeg)
![whatsapp image 2018-10-27 at 11 22 15 am](https://user-images.githubusercontent.com/44457119/47600196-dbe33a80-d9da-11e8-93c5-fb603794c3c6.jpeg)

**Comment by swashata** [comment]
Nah. Maybe you can do something with the letter W

**Comment by Amitavo** [comment]
Ok.. Will give another try

**Comment by swashata** [comment]
Closing this issue, when you are ready, feel free to open a new one.
