### ISSUE TITLE
Updating the scripts.

### ISSUE THREAD

**Issue by kmgalanakis** [swashata/wp-webpack-script#288]
Hello. Thank you for these excellent scripts. I just wanted to ask how should we handle the updating of the script, for when our project was created some time ago?

Thank you in advance.

**Comment by swashata** [comment]
Hello,

Updating is like updating any `package.json` entry.

## Updating Dependencies

### Manually editing `package.json`

Edit your `package.json` file and update the versions of `@wpackio/scripts` and `@wpackio/endpoint`.

### If using NPM

```bash
npm update
```

Or specifically

```bash
npm i -D @wpackio/scripts
npm i @wpackio/endpoint
```

This will update the two dependencies your project needs.

### If using YARN

```bash
yarn upgrade-interactive --latest
```

And select `@wpackio/endpoint` and `@wpackio/scripts`.

### Post Update

There could've been some changes in file format or maybe some new config file was introduced. In any case, run

```bash
yarn bootstrap
```

Or if using NPM

```bash
npm run bootstrap
```

To make sure your config is all correct.

Would you mind adding this to the docs?

**Comment by halmos** [comment]
i think that ` @wpackio/endpoint` should be ` @wpackio/entrypoint`?

also, it would be great to include information about the composer update as well. I assume that the npm and composer package versions need to be kept in sync?

**Comment by swashata** [comment]
Yes you are absolutely right about it. You need to update composer package too.

I would be very grateful if you can add it to the docs

**Comment by swashata** [comment]
https://wpack.io/tutorials/updating-wpackio/
