### ISSUE TITLE
outputPath as subfolder

### ISSUE THREAD

**Issue by TrilipuT** [swashata/wp-webpack-script#606]
Thanks for great toolkit!
If I use subfolder as an output path `outputPath: 'assets/built'` it breaks the dynamic import functionality because of the wrong variable name.
```js
/* wpack.io publicPath */
window.__wpackIotestassets/built='https://www.wp.local/wp-content/themes/test/assets/built/';
```
```js
window["__wpackIo".concat("test").concat("assets/built")]
```
I think appname and outputPath should be escaped/sanitized.
For example, WP has `sanitize_key()` function for this.

**Comment by swashata** [comment]
Hello,

Thank you for pointing this out. Do you mind sending in a PR for this?
