### ISSUE TITLE
How to work with static files ?

### ISSUE THREAD

**Issue by proov** [swashata/wp-webpack-script#685]
Hello,

I am setting up wpack.io in a new Wordpress Starter with Bedrock & Timber. I've extended the Webpack config to add a first plugin : [SVG Spritemap Plugin](https://github.com/cascornelissen/svg-spritemap-webpack-plugin). At the moment everything is perfect and fast :) 

Now the next step is to handle images / static files, but i dont know in which way to go ^^ and i found nothing in the documentation :/

I would like to view static files during development and have a compression when compiling to production.

I was thinking about a `static` folder in `src/theme` (or maybe better at the theme root) and extend Webpack config to copy+compress it in `dist/` folder when compiling for production. You think it is good or there is a better way ?

EDIT: hum, no it's not a good solution because it would be necessary to change the path to `/dist` in all templates 😅 
Well i guess, i'm going to keep all the static files in a `static` folder at the root of the theme and compress files inside when compiling to production..

Thanks :)

**Comment by swashata** [comment]
Hello,

When you import a static file like

```js
import svgURL from '../static/mystuff.svg'
```

It is automatically copied to the `/dist` during build. So you don't have to change paths or copy anything. You just need to make sure you have proper loader for the type of file you are importing.

**Comment by proov** [comment]
Ok great ! And what i have to write in HTML files when i want to display an image ?

**Comment by swashata** [comment]
Hello,

Sorry for not being clear. The above is what you'd do in a JS file. For HTML or PHP, you have rely on server side logic to get the static asset. This library is for managing front-end things only.

**Comment by simplenotezy** [comment]
@swashata ? Makes no sense. I'd like some help on this one as well; "How can one fetch a static asset, like an image, in the HTML?"

**Comment by simplenotezy** [comment]
This seems to do the trick: https://github.com/swashata/wpackio-enqueue/issues/4
