### ISSUE TITLE
Appname camelCase with numbers

### ISSUE THREAD

**Issue by hardeepkhehra** [swashata/wp-webpack-script#740]
I'm building a plugin and brand called "bed66" but wpack.io fails to start because plugin is not considered in camelcase. 

Any advice or guidance?

**Comment by hardeepkhehra** [comment]
✖ could not start server.
=========================

 please review the following errors 

  ❯  appName must be in camelCase in project config.
  ❯  Currently bed66, try bed66

**Comment by swashata** [comment]
Hi,

This is a restriction in naming things. Simply try bedSixSix or bedSixtySix

**Comment by hardeepkhehra** [comment]
Yes, that is what I did to get around the restriction.  Thank you.
