### ISSUE TITLE
Yarn start is trying to enqueue /dist/ files

### ISSUE THREAD

**Issue by simplenotezy** [swashata/wp-webpack-script#820]
Previously `yarn start` worked just fine, but now it doesn't seem to work. I get:

`Unexpected token '<'` because the enqueued assets are trying to be fetched from /dist/ folder, and I guess this folder is empty when I am running `yarn start`. What am I doing wrong?

I am enqueuing like this:

		$this->instantButler->get_enqueue()->enqueue( 'app', 'butler', ['js' => false, 'css' => true] );
		$this->instantButler->get_enqueue()->enqueue( 'app', 'admin', ['js' => false, 'css' => true] );

I didn't change anything, and previously it worked fine.

**Comment by swashata** [comment]
Hello,

`Unexpected token '<'` is coming from some sort of module files. It has nothing to do with how you enqueue with PHP. Do check the file associated with the error. It will give you more insight.

**Comment by simplenotezy** [comment]
@swashata I don't agree. If I run `yarn build` it works just fine. It's saying `Unexpected token '<'` because the file it tries to enqueue does not exist.

**Comment by swashata** [comment]
Please share complete error log here

**Comment by freddiemixell** [comment]
Sounds like WordPress is returning a 404 html page which is why you have the < in the error. 

I would check to make sure you the paths to your assets are correct. I had this happen to me and it was due to a typo in the path to my js.
