### ISSUE TITLE
`__webpack_public_path__` is undefined

### ISSUE THREAD

**Issue by jmfurlott** [swashata/wp-webpack-script#881]
After working through the docs [here](https://wpack.io/concepts/how-publicpath-works/), I had trouble getting code splitting working using the `React.lazy(() => import('../component'))` due to a 404 on the split bundles being generated.  The generated path to the split bundle looked like this `http://localhost/existing-slug/undefinedwpack/7-c401d14a.js`

After doing some digging, it turned out `__webpack_public_path__` was never getting set based on the inserted wpack script (`if (__WPACK__) ...` file).  After setting the variable by hand, at the entry point, it worked fine from there on.  Example below:

```js
__webpack_public_path__ = window.__wpackIoappNamePublicPath;

import ...
```

Not sure what would be causing this?

**Comment by maximaLzdnb** [comment]
Tagging in on this issue, I seem to have something very similar to this.

I'm developping a theme, and my structure is something like this :

myTheme
- src
- - img
- - - bg.png
- - - img2.png
- - - ...

and when I import these in my JS file like so, by using a webpack alias 'Images' (and even without an alias) :

`import bgTile from 'Images/bg.png';`

this works in dev-server mode (`wpackio-scripts start`), however it outputs something really weird in build : 

`undefinedapp/assets/bg-1b7cccae.png`

The worst thing about this is that it does this only in my JS.. Using the alias in my SCSS outputs the right URL both in dev and build.

I've tried a number of things, ranging from upgrading my wpackio version all the way to trying out custom images loaders, and nothing gave a working result, it's always the very same weird "undefined".

I develop with Windows and Windows Subsystem for Linux. I can't really try anything else right now, but if OP has the same issue and the same env, it might come from that, I do remember having troubles with gatsby.js with WSL. Any idea?

**Comment by swashata** [comment]
Hi,

The `undefined` part is the `appName` of `wpackio.project.js` file. Please make sure you have it.

Also for more help, kindly provide a reproducible repo.

**Comment by jmfurlott** [comment]
@swashata I can try to set up but a repo that reproduces the problem as the issue is on a closed soruce repo currently.  I have confirmed that we have an `appName` in the project config atm

**Comment by swashata** [comment]
Hi,

One more thing about this is, wpackio/enqueue from PHP sets the value. Are you sure it's being set? It uses the following hooks

```php
		// wp_head is done before printing any script or style tag
		\add_action( 'wp_head', [ $this, 'printPublicPath' ], -1000 );
		// in case of admin, styles and scripts are printed before admin_head
		// so we use admin_print_scripts
		\add_action( 'admin_print_scripts', [ $this, 'printPublicPath' ], -1000 );
```

So maybe, it never gets executed.

**Comment by a-barbieri** [comment]
I have the same problem but it happens only in production. I don't get what's missing....
