### ISSUE TITLE
No clear error when using eslint with Typescript

### ISSUE THREAD

**Issue by icyd** [swashata/wp-webpack-script#967]
Hi, just trying this package, looks promising. Nevertheless I found up that trying to enabling eslint with typescript, I got the error `please install fork-ts-checker-webpack-plugin package`. I proceeded to install it but still got the same error. I checked the code in the file `WebpackConfigHelper.js` between lines 279 and 295, the error was generated because **Typescript** wasn't installed, I don't know if is an error on the dependencies, or just I missed a step setting everything up. Regards.

**Comment by swashata** [comment]
Hi,

Typescript is indeed needed if you have typescript files in your repo. I will close this issue for now. If you can improve the error message, feel free to add a PR.
